---
title: "Code"
author: "Clara Livingston"
date: "May 25, 2018"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(ggplot2)
```

#Data Join
```{r}
state <- read.csv("StateData.csv")
team <- read.csv("TeamData.csv",stringsAsFactors = TRUE)

statestuff <- data.frame(state.abb,state.name)
colnames(statestuff) <- c("State","StateName")
state <- full_join(state,statestuff)
state$StateName <- as.character(state$StateName)
state <- state%>%mutate(StateAbb=State,State=ifelse(State=="DC","District of Columbia",as.character(StateName)))
AllData <- right_join(state,team)
write.csv(AllData,"AllData.csv")

# make strings numeric
AllData$Capacity <- as.numeric(gsub(",", "", AllData$Capacity) )
AllData$FranchiseValue <- as.numeric(gsub(",", "", AllData$FranchiseValue) )

# making percent of home wins as variable

AllData <- AllData %>% mutate(WinPct = HomeWins/HomeGames)
```

# EDA

```{r}
# Team Level Variables
# Basic EDA
# #
boxplot(AllData$WinPct)
summary(AllData$WinPct)
# # Sport
table(AllData$Type)

# # Capacity
hist(AllData$Capacity)
summary(AllData$Capacity)
ggplot(AllData, aes(x=Type, y = Capacity)) + geom_boxplot() # interaction needed for stadium size and sport

# # FranchiseValue
hist(AllData$FranchiseValue)
summary(AllData$FranchiseValue)
ggplot(AllData, aes(x=Type, y = FranchiseValue)) + geom_boxplot() # interaction needed for franchise and sport

# # Attendance
hist(AllData$Attendence)
summary(AllData$Attendence)
ggplot(AllData, aes(x=Type, y = Attendence)) + geom_boxplot() # interaction needed for franchise and sport

# # Year
hist(AllData$Year.opened)
tapply(AllData$Capacity, AllData$Year.opened, mean)
tapply(AllData$Year.opened, AllData$Type,mean) # hockey and basketball have newest stadiums and baseball and football have older, with baseball being oldest
```

Potential Interactions

Significant Looking interactions: Capacity and Attandence
```{r}
# Level 1 Interactions

# make capacity a factor for data exploration
AllData$CapFactor <- cut(AllData$Capacity, breaks = c(0, 18578, 27000,  62250,100000), labels = c("1st Q", "2nd Q", "3rd Q", "4th Q"))


#cap and year
ggplot(AllData, aes(x=Year.opened, y = Capacity, color = WinPct)) + geom_point()
ggplot(AllData, aes(x=Year.opened,y = WinPct)) + geom_point() + facet_wrap(~CapFactor) # doesn't appear to be an interaction

#cap and sport
ggplot(AllData, aes(x=Capacity,y = WinPct)) + geom_point() + facet_wrap(~Type) # doesn't appear to be an interaction

#cap and franchise $$
ggplot(AllData, aes(x=FranchiseValue,y = WinPct)) + geom_point() + facet_wrap(~CapFactor) # doesn't appear to be an interaction

#cap and attendance
ggplot(AllData, aes(x=Attendence,y = WinPct)) + geom_point() + facet_wrap(~CapFactor) +geom_smooth(method=lm) # Interaction
```
